---
  - name: install kvm packages on Debian 10,9,..,Ubuntu 20.04,18.04,e.t.c
    package:
      name:
        - bridge-utils
        - qemu-kvm
        - virtinst
        - libvirt-daemon
        - virt-manager
      state: latest
      update_cache: yes
      cache_valid_time: 5400
      allow_unauthenticated: yes
    become: true
